# create this file under AAVE_BROWNIE_PY


dependencies:
  -aave/protocal-v2@1.0.1
compiler:
  solc:
    remappings:
      -'@aave=aave/protocal-v2@1.0.1'

networks:
  kovan:
    weth_token: '0x5F382a2B7aAdc9F5810d617741DFC2706f724845'//recheck this metamask address
    lending_pool_addresses_provider: '0x88757f2f99175387ab4c6a4b3067c77a695b0349'//https://docs.aave.com/developers/deployed-contracts/deployed-contracts(mainnet) video time 1:42:53
    
mainnet-fork: 
  weth_token: '0xc0F382a2B7aAdc9F5810d617741DFC2706f724845'//rechck this address with ref.video 1:28:44
  lending_pool_addresses_provider: '0xb53c1a33016b2dc2ff3653530bff1848a515c8c5'//https://docs.aave.com/developers/deployed-contracts/deployed-contracts(mainnet) video time 1:42:45
wallets:
  from_key:${PRIVATE_KEY}
